include ../make.vars

#CXXFLAGS += -std=c++14
CXXFLAGS += -g
#LDFLAGS += -lpthread
#CXXFLAGS += -O2

TARGETS += exename

all : $(TARGETS)

exename : exename.o
	$(CXX) -o $@ $(CXXFLAGS) $(LDFLAGS) exename.o

clean:
	rm -f *.o $(TARGETS)

include ../make.rules
