ORDERED += ps1_questions.pdf
ORDERED += ps1_solns.pdf
ORDERED += ps2_questions.pdf
ORDERED += ps2_solns.pdf
ORDERED += ps3_questions.pdf
ORDERED += ps3_solns.pdf
ORDERED += ps4_questions.pdf
ORDERED += ps4_solns.pdf
ORDERED += ps5_questions.pdf
ORDERED += ps5_solns.pdf
ORDERED += term_test_with_solns.pdf
ORDERED += ps6_questions.pdf
ORDERED += ps6_solns.pdf
ORDERED += ps7_questions.pdf
ORDERED += ps7_solns.pdf
ORDERED += ps8_questions.pdf
ORDERED += ps8_solns.pdf
ORDERED += ps9_questions.pdf
ORDERED += ps9_solns.pdf
ORDERED += ps10_questions.pdf
ORDERED += ps10_solns.pdf

solutions.pdf : $(ORDERED) GNUmakefile
	pdftk $(ORDERED) cat output $@
