THISDIR := phy485-optics

include ../make.bookvars

FIGURES := ../../figures/phy485

#ONCEFLAGS := -justonce

SOURCE_DIRS += appendix
SOURCE_DIRS += $(FIGURES)

GENERATED_SOURCES += mathematica.tex 

include ../make.rules
