THISDIR := phy485-optics
THISBOOK := phy485

include ../make.bookvars

FIGURES := ../../figures/$(THISBOOK)

#ONCEFLAGS := -justonce

SOURCE_DIRS += appendix
SOURCE_DIRS += $(FIGURES)

GENERATED_SOURCES += mathematica.tex 

include ../make.rules
