THISDIR := miscphysics

include ../make.vars

SOURCE_DIRS += algebra
SOURCE_DIRS += calculus
SOURCE_DIRS += cross
SOURCE_DIRS += electrodynamics
SOURCE_DIRS += feynman
SOURCE_DIRS += figures
SOURCE_DIRS += fletcher
SOURCE_DIRS += fourier
SOURCE_DIRS += maxwell
SOURCE_DIRS += probability
SOURCE_DIRS += qm
SOURCE_DIRS += relativity
SOURCE_DIRS += sort

ORIG_FILES += ../gabook/pendulumDouble.png

GENERATED_SOURCES := cronology.tex

include ../make.rules
