#!/usr/bin/perl

my @pfiles =
(
{
   FILE => 'RelEM1-11.pdf',
   DESC => qq(space, time and Gallilean relativity (1-6); speed of light and Einsteins relativity principle (7-10); relativity of simultaneity (11).),
},
{
   FILE => 'RelEM12-26.pdf',
   DESC => qq(spacetime, spacetime points, worldlines, interval (12-14) ; invariance of infinitesimal intervals (15-17); geometry of spacetime, lightlike, spacelike, timelike intervals, and worldlines (18-22); proper time (23-24); invariance of finite intervals (25-26).),
},
{
   FILE => 'RelEM27-44.pdf',
   DESC => qq(
analogy with rotations and derivation of Lorentz transformations (27-32); Minkowski space diagram of boosted frame (32.1) ; Using Minkowski diagram to see the perils of superluminal propagation (32.3); nonrelativistic limit of boosts (33); number of parameters of Lorentz transformations (34-35); introducing four-vectors, the metric tensor, the invariant ``dot-product and SO(1,3) (36-40); the Poincare group (41); the convenience of ``upper'' and ``lower''indices (42-43); tensors (44)),
},
{
   FILE => 'RelEMpp52-56.pdf',
   DESC => qq(equation of motion, symmetries, and conserved quantities (energy-momentum 4 vector) from relativistic particle action.),
},
{
   FILE => 'RelEMpp56.1-73.pdf',
   DESC => qq(comments on mass, energy, momentum, and massless particles (56.1-58); particles in external fields: Lorentz scalar field (59-62); reminder of a vector field under spatial rotations (63) and a Lorentz vector field (64-65) [Tuesday, Feb. 1]; the action for a relativistic particle in an external 4-vector field (65-66); the equation of motion of a relativistic particle in an external electromagnetic (4-vector) field (67,68,73) [Wednesday, Feb. 2]; mathematical interlude: (69-72): on 3x3 antisymmetric matrices, 3-vectors, and totally antisymmetric 3-index tensor - please read by yourselves, preferably by Wed., Feb. 2 class! (this is important, we will also soon need the 4-dimensional generalization)),
},
{
   FILE => 'RelEMpp74-83.pdf',
   DESC => qq(gauge transformations in 3-vector language (74); energy of a relativistic particle in EM field (75); variational principle and equation of motion in 4-vector form (76-77); the field strength tensor (78-80); the fourth equation of motion (81) ; Lorentz transformation of the strength tensor (82) ; extra reading for the mathematically minded: gauge field, strength tensor, and gauge transformations in differential form language, not to be covered in class (83)),
},
{
   FILE => 'RelEMpp84-102.pdf',
   DESC => qq(relativity, gauge invariance, and superposition principles and the action for the electromagnetic field coupled to charged particles (91-95); the 4-current and its physical interpretation (96-102), including a needed mathematical interlude on delta-functions of functions (98-100)),
},
{
   FILE => 'RelEMpp103-113.pdf',
   DESC => qq(variational principle for the electromagnetic field and the relevant boundary conditions (103-105); the second set of Maxwell's equations from the variational principle (106-108); Maxwell's equations in vacuum and the wave equation in the non-relativistic Coulomb gauge (109-111)),
},
{
   FILE => 'RelEMpp114-127.pdf',
   DESC => qq(reminder on wave equations (115); reminder on Fourier series and integral (115-117); Fourier expansion of the EM potential in Coulomb gauge and equation of motion for the spatial Fourier components (118-119); the general solution of Maxwell's equations in vacuum (120-121)),
},
{
   FILE => 'RelEMpp114-127.pdf',
   DESC => qq(properties of monochromatic plane EM waves (122-124); energy and energy flux of the EM field and energy conservation from the equations of motion (125-127)),
},
{
   FILE => 'RelEMpp128-135.pdf',
   DESC => qq(energy flux and momentum density of the EM wave (128-129); radiation pressure, its discovery and significance in physics (130-131); EM fields of moving charges: setting up the wave equation with a source (132-133); the convenience of Lorentz gauge in the study of radiation (134); reminder on Green's functions from electrostatics (135)),
},
{
   FILE => 'RelEMpp136-146.pdf',
   DESC => qq(continued remainder of electrostatic Green's function (136); the retarded Green's function of the d'Alembert operator: derivation and properties (137-140); the solution of the d'Alembert equation with a source: retarded potentials (141-142); retarded time ; the Lienard-Wiechert potentials (143-146)),
},
{
   FILE => 'RelEMpp147-165.pdf',
   DESC => qq(EM fields of a moving source (147-148+HW5); a particle at rest (148); a constant velocity particle (149-152); behavior of EM fields ``at infinity'' for a general-worldline source and radiation (152-153) ; radiated power (154); fields in the ``wave zone'' and discussions of approximations made (155-159); EM fields due to electric dipole radiation (160-163); Poynting vector, angular distribution, and power of dipole radiation (164-165)),
},
{
   FILE => 'RelEMpp166-180.pdf',
   DESC => qq(spacetime translation invariance of the EM field action and the conservation of the energy-momentum tensor (170-172); properties of the energy-momentum tensor (172.1); the meaning of its components: energy ; the force on a surface element of a body (177-178); a plane wave example (179-180).),
},
{
   FILE => 'RelEMpp181-195.pdf',
   DESC => qq(the Lagrangian for a system of non relativistic charged particles to zeroth order in \\((v/c)\\): electrostatic energy of a system of charges and .mass renormalization ; (182-189) the EM potentials to order \\((v/c)^2\\) (190-193); the ``Darwin Lagrangian.  and Hamiltonian for a system of non-relativistic charged particles to order \\((v/c)^2\\) and its many uses in physics (194-195) ; (198.1-200) (last topic): attempt to go to the next order \\((v/c)^3\\) - radiation damping, the limitations of classical electrodynamics, and the relevant time/length/energy scales.
),
},
) ;

print "
The current path for Prof. Poppitz's handouts is
\\href{http://www.physics.utoronto.ca/~poppitz/poppitz/PHY450.html}{http://www.physics.utoronto.ca/~poppitz/poppitz/PHY450.html}.  These were a valuable resource when I took the course.  At the time of this writing (accessed Dec, 2014) the following files were available.  The descriptions are from the 2011 versions of the files and may no longer match exactly.

\\begin{itemize}
" ;

my $path = "http://www.physics.utoronto.ca/~poppitz/poppitz/PHY450_files/" ;

foreach ( @pfiles )
{
   my $f = $_->{'FILE'} ;
   my $desc = $_->{'DESC'} ;

print "
\\item \\phantomsection \\label{path:phy450:$f} \\href{$path$f}{$f}

$desc
" ;
}

print "
\\end{itemize}
" ;
