#http://ocw.mit.edu/courses/electrical-engineering-and-computer-science/6-013-electromagnetics-and-applications-fall-2005/textbook-with-video-demonstrations/

ORDERED += dedication.pdf
ORDERED += preface.pdf
ORDERED += contents.pdf
ORDERED += 01.pdf
ORDERED += 02.pdf
ORDERED += 03.pdf
ORDERED += 04.pdf
ORDERED += 05.pdf
ORDERED += 06.pdf
ORDERED += 07.pdf
ORDERED += 08.pdf
ORDERED += 09.pdf
ORDERED += 10.pdf
ORDERED += 11.pdf
ORDERED += 12.pdf
ORDERED += 13.pdf
ORDERED += 14.pdf
ORDERED += 15.pdf
ORDERED += a1.pdf
ORDERED += a2.pdf

mit6_013.pdf : $(ORDERED)
	pdftk $(ORDERED) cat output $@
