#-------------------------------------------------
# local clang build related stuff:

GCCPATH=/vbs/bldsupp.linux1/linuxamd64/gcc-4.2.2-31309

LDFLAGS += -Wl,-rpath,$(GCCPATH)/lib64
LDFLAGS += -Wl,-rpath-link,$(GCCPATH)/lib64

CXX := $(GCCPATH)/bin/g++

#-------------------------------------------------
# Built two versions of clang, one for debugging
# into rewritersample.cpp:
#-------------------------------------------------
#CONFIG_RELEASE = Debug+Asserts
CLANGPATH=$(HOME)/clang/debug
#-------------------------------------------------
#CONFIG_RELEASE = Release+Asserts
#CLANGPATH=$(HOME)/clang/optimized
#-------------------------------------------------

LLVM_BIN_PATH := $(CLANGPATH)/bin/
