#!/usr/bin/perl

my $doGabook = 1 ;
use Getopt::Long;

GetOptions( 'gabook!' => \$doGabook ) ;

#use warnings ;
#use strict ;

my @gabook =
({
   SOURCE => 'gaMaxwell',
   DATE => 'July 12, 2008',
   TITLE => qq(Back to Maxwell's equations),
   REF => 'PJMaxwell2',
},{
   SOURCE => 'maxwellToTensor',
   DATE => 'September 7, 2008',
   TITLE => qq(Tensor relations from bivector field equation),
   REF => 'PJMaxwellTensor',
},{
   SOURCE => 'multivectorTaylors',
   DATE => 'April 28, 2009',
   TITLE => qq(Developing some intuition for Multivariable and Multivector Taylor Series),
   REF => 'PJmultiTaylors',
},{
   SOURCE => 'noethersField',
   DATE => 'October 29, 2008',
   TITLE => qq(Field form of Noether's Law),
   REF => 'PJNoethersField',
},{
   SOURCE => 'noethersLorentzForce',
   DATE => 'October 22, 2008',
   TITLE => qq(Lorentz transform Noether current for interaction Lagrangian),
   REF => 'PJLorentzTxInteraction',
},{
   SOURCE => '4dFourier',
   DATE => 'February 1, 2009',
   TITLE => qq(4D Fourier transforms applied to Maxwell's equation),
   REF => 'PJ4dFourier',
},{
   SOURCE => 'angleBetweenLineAndPlane',
   TITLE => qq(Angle between geometric elements),
   DATE => 'March 17, 2008',
   REF => 'angleBetweenLineAndPlane',
},{
   SOURCE => 'angularAcc',
   DATE => 'June 10, 2008',
   TITLE => qq(Angular Velocity and Acceleration.  Again),
   REF => 'PJAngAcc',
},{
   SOURCE => 'angularAccCross',
   DATE => 'July 8, 2008',
   TITLE => qq(Cross product Radial decomposition),
   REF => 'PJAngAccCross',
},{
   SOURCE => 'angularVelocity',
   DATE => 'January 29, 2008',
   TITLE => qq(Rotational dynamics),
   REF => 'PJAngVel',
},{
   SOURCE => 'boostMaxwellLagrangian',
   DATE => 'October 19, 2008',
   TITLE => qq(Lorentz Invariance of Maxwell Lagrangian),
   REF => 'PJBoostMaxwell',
},{
   SOURCE => 'canonicalMomentum',
   DATE => 'September 1, 2008',
   TITLE => qq(Vector canonical momentum),
   REF => 'PJCanMomentum',
},{
   SOURCE => 'electricFieldEnergy',
   DATE => 'January 3, 2009',
   TITLE => qq(Field and wave energy and momentum),
   REF => 'PJelectricFieldEnergy',
},{
   SOURCE => 'emWave',
   DATE => 'January 25, 2009',
   TITLE => qq(Electrodynamic wave equation solutions),
   REF => 'PJemWave',
},{
   SOURCE => 'enMTensor',
   DATE => 'February 17, 2009',
   TITLE => qq(Energy momentum tensor relation to Lorentz force),
   REF => 'en_m_tensor',
},{
   SOURCE => 'energyMomentumTensor',
   DATE => 'January 1, 2009',
   TITLE => qq(Energy momentum tensor),
   REF => 'PJemstresstensor',
},{
   SOURCE => 'eulerLagrange',
   DATE => 'October 13, 2008',
   TITLE => qq(Euler Lagrange Equations),
   REF => 'PJEulerLagrange',
},{
   SOURCE => 'eulerangle',
   DATE => 'November 1, 2008',
   TITLE => qq(Euler Angle Notes),
   REF => 'eulerangle',
},{
   SOURCE => 'fieldLagrangian',
   DATE => 'October 10, 2008',
   TITLE => qq(Derivation of Euler-Lagrange field equations),
   REF => 'PJFieldLagrangian',
},{
   SOURCE => 'firstorderFourierMaxwell',
   DATE => 'January 31, 2009',
   TITLE => qq(First order Fourier transform solution of Maxwell's equation),
   REF => 'PJfirstOrderMaxwell',
},{
   SOURCE => 'fourierMaxwell',
   DATE => 'January 29, 2009',
   TITLE => qq(Fourier transform solutions to Maxwell's equation),
   REF => 'PJfourierMaxwellSecondOrder',
},{
   SOURCE => 'fourierSeriesMaxwell',
   DATE => 'February 3, 2009',
   TITLE => qq(Fourier series Vacuum Maxwell's equations),
   REF => 'PJFourierVacuum',
},{
   SOURCE => 'fourierTx',
   DATE => 'January 9, 2009',
   TITLE => qq(Some Fourier transform notes),
   REF => 'PJqmFourier',
},{
   SOURCE => 'gaWikiUnitDerivative',
   DATE => 'October 16, 2007',
   TITLE => qq(Derivatives of a unit vector),
   REF => 'PJUnitDer',
},{
   SOURCE => 'gafpLorentz',
   DATE => 'August 16, 2008',
   TITLE => qq(Lorentz force Law),
   REF => 'PJSrGAFPLorentzForce',
},{
   SOURCE => 'gamma',
   DATE => 'December 13, 2008',
   TITLE => qq(Gamma Matrices),
   REF => 'PJDiracGamma',
},{
   SOURCE => 'heatFourier',
   DATE => 'January 19, 2009',
   TITLE => qq(Fourier Solutions to Heat and Wave equations),
   REF => 'PJheatFourier',
},{
   SOURCE => 'keRotation',
   DATE => 'April 30, 2008',
   TITLE => qq(Kinetic Energy in rotational frame),
   REF => 'PJKeRot',
},{
   SOURCE => 'lagrangianFieldDensity',
   DATE => 'September 8, 2008',
   TITLE => qq(Direct variation of Maxwell equations),
   REF => 'PJMaxwellLagrangian',
},{
   SOURCE => 'lorentzForce',
   DATE => 'October 8, 2008',
   TITLE => qq(Revisit Lorentz force from Lagrangian),
   REF => 'PJSrLorentzForce',
},{
   SOURCE => 'planewave',
   DATE => 'February 8, 2009',
   TITLE => qq(Plane wave Fourier series solutions to the Maxwell vacuum equation),
   REF => 'PJplaneWave',
},{
   SOURCE => 'poisson',
   DATE => 'February 18, 2009',
   TITLE => qq(Poisson and retarded Potential Green's functions from Fourier kernels),
   REF => 'PJpoisson',
},{
   SOURCE => 'poynting',
   DATE => 'December 29, 2008',
   TITLE => qq(Poynting vector and Electromagnetic Energy conservation),
   REF => 'PJpoynting',
},{
   SOURCE => 'poyntingRate',
   DATE => 'January 18, 2009',
   TITLE => qq(Time rate of change of the Poynting vector, and its conservation law),
   REF => 'PJpoyntingRate',
},{
   SOURCE => 'projGeneralizedDotProd',
   DATE => 'May 17, 2008',
   TITLE => qq(Projection with generalized dot product),
   REF => 'PJprojGen',
},{
   SOURCE => 'projectionWithMatrixComparison',
   DATE => 'April 11, 2008',
   TITLE => qq(Matrix review),
   REF => 'matrixReview',
},{
   SOURCE => 'radialVectorDerivatives',
   DATE => 'October 22, 2007',
   TITLE => qq(Radial components of vector derivatives),
   REF => 'PJRadialDer',
},{
   SOURCE => 'rayleighJeans',
   DATE => 'December 27, 2008',
   TITLE => qq(Rayleigh-Jeans Law Notes),
   REF => 'PJrayleighJeans',
},{
   SOURCE => 'rotor',
   DATE => 'February 19, 2008',
   TITLE => qq(Rotor Notes),
   REF => 'rotor',
},{
   SOURCE => 'srLagrangian',
   DATE => 'August 21, 2008',
   TITLE => qq(Covariant Lagrangian, and electrodynamic potential),
   REF => 'PJSrLagrangian',
},{
   SOURCE => 'stokesRevisited',
   DATE => 'September 27, 2008',
   TITLE => qq(Stokes Law revisited with algebraic enumeration of boundary),
   REF => 'PJStokes2',
},{
   SOURCE => 'stressEnergyLorentz',
   DATE => 'February 13, 2009',
   TITLE => qq(Lorentz force relation to the energy momentum tensor),
   REF => 'PJstressEnergyLorentz',
},{
   SOURCE => 'vectorIntegralRelations',
   DATE => 'September 18, 2008',
   TITLE => qq(Stokes law in wedge product form),
   REF => 'PJStokes1',
},{
   SOURCE => 'vectorMaxwellsProjection',
   DATE => 'September 9, 2008',
   TITLE => qq(Vector forms of Maxwell's equations as projection and rejection operations),
   REF => 'PJMaxwellProj',
},{
   SOURCE => 'waveEqn',
   DATE => 'November 30, 2008',
   TITLE => qq(Expressing wave equation exponential solutions using four vectors),
   REF => 'PJwaveFourVector',
},{
   SOURCE => 'waveFourier',
   DATE => 'January 26, 2009',
   TITLE => qq(Fourier transform solutions to the wave equation),
   REF => 'PJwaveFourier',
},{
   SOURCE => 'biotSavart',
   DATE => 'April 18, 2009',
   TITLE => qq(Biot Savart Derivation),
   REF => 'biotSavart',
},{
   SOURCE => 'bivector',
   DATE => 'March 9, 2008',
   REF => 'bivector',
   TITLE => qq(Bivector Geometry),
},{
   SOURCE => 'bohr',
   DATE => 'December 11, 2008',
   TITLE => qq(Bohr Model),
   REF => 'bohr',
},{
   SOURCE => 'cauchyGradient',
   DATE => 'August 13, 2008',
   TITLE => qq(Cauchy Equations expressed as a gradient),
   REF => 'cauchyGradient',
},{
   SOURCE => 'diracLagrangian',
   DATE => 'December 21, 2008',
   TITLE => qq(Dirac Lagrangian),
   REF => 'diracLagrangian',
},{
   SOURCE => 'lorentzForcePQA',
   DATE => 'April 15, 2009',
   TITLE => qq(Lorentz force Lagrangian with conjugate momentum),
   REF => 'lorentzForcePQA',
},{
   SOURCE => 'maxwellTensorFromLagrangian',
   DATE => 'April 20, 2009',
   TITLE => qq(Tensor derivation of non-dual Maxwell equation from Lagrangian),
   REF => 'maxwellTensorFromLagrangian',
},{
   SOURCE => 'maxwellTensorLagrangian',
   DATE => 'October 12, 2008',
   TITLE => qq(Tensor Derivation of Covariant Lorentz Force from Lagrangian),
   REF => 'maxwellTensorLagrangian',
},{
   SOURCE => 'nvolume',
   DATE => 'February 26, 2009',
   TITLE => qq(Spherical and hyperspherical parametrization),
   REF => 'nvolume',
},{
   SOURCE => 'obliqueProj',
   DATE => 'May 16, 2008',
   TITLE => qq(Oblique projection and reciprocal frame vectors),
   REF => 'obliqueProj',
},{
   SOURCE => 'potentialFourier',
   DATE => 'February 7, 2009',
   TITLE => qq(Lorentz Gauge Fourier Vacuum potential solutions),
   REF => 'potentialFourier',
},{
   SOURCE => 'radial',
   DATE => 'January 13, 2009',
   TITLE => qq(Polar velocity and acceleration),
   REF => 'radial',
},{
   SOURCE => 'sphericalPolar',
   DATE => 'November 13, 2008',
   TITLE => qq(Spherical polar coordinates),
   REF => 'sphericalPolar',
},{
   SOURCE => 'stokesMaxwellApplication',
   DATE => 'September 26, 2008',
   TITLE => qq(Application of Stokes Integrals to Maxwell's Equation),
   REF => 'stokesMaxwellApplication',
},{
   TITLE => qq(Vector Differential Identities),
   REF => 'vectorDifferentialIdentities',
   SOURCE => 'vectorDifferentialIdentities',
   DATE => 'January 5, 2009',
},{
   SOURCE => 'bladegradereduction',
   DATE => 'March 25, 2008',
   TITLE => qq(Blade grade reduction),
   REF => 'bladegradereduction',
},{
   SOURCE => 'chargeArcElement',
   DATE => 'November 23, 2008',
   TITLE => qq(Field due to line charge in arc),
   REF => 'chargeArcElement',
},{
   SOURCE => 'chargeLineElement',
   DATE => 'November 23, 2008',
   TITLE => qq(Charge line element),
   REF => 'chargeLineElement',
},{
   SOURCE => 'complex',
   DATE => 'November 8, 2008',
   TITLE => qq(Hyper complex numbers and symplectic structure),
   REF => 'complex',
},{
   SOURCE => 'dcPower',
   DATE => 'January 6, 2009',
   TITLE => qq(DC Power consumption formula for resistive load),
   REF => 'dcPower',
},{
   SOURCE => 'electronRotor',
   DATE => 'March 18, 2009',
   TITLE => qq(Lorentz force rotor formulation),
   REF => 'electronRotor',
},{
   SOURCE => 'emBivectorMetricDependencies',
   DATE => 'September 5, 2008',
   TITLE => qq(Metric signature dependencies),
   REF => 'emBivectorMetricDependencies',
},{
   SOURCE => 'emPotential',
   DATE => 'August 15, 2008',
   TITLE => qq(Four vector potential),
   REF => 'emPotential',
},{
   REF => 'fourierNotation',
   TITLE => qq(A cheatsheet for Fourier transform conventions),
   SOURCE => 'fourierNotation',
   DATE => 'January 21, 2009',
},{
   SOURCE => 'fourvecDotinvariance',
   DATE => 'August 1, 2008',
   TITLE => qq(Four vector dot product invariance and Lorentz rotors),
   REF => 'fourvecDotinvariance',
},{
   SOURCE => 'inertialTensor',
   DATE => 'February 15, 2008',
   TITLE => qq(Inertia Tensor),
   REF => 'inertialTensor',
},{
   SOURCE => 'kvectorExponential',
   DATE => 'March 12, 2008',
   TITLE => qq(Exponential of a blade),
   REF => 'kvectorExponential',
},{
   SOURCE => 'laplace',
   DATE => 'February 28, 2008',
   TITLE => qq(Exponential Solutions to Laplace Equation in \\R{N}),
   REF => 'laplace',
},{
   SOURCE => 'legendre',
   DATE => 'February 4, 2008',
   TITLE => qq(Legendre Polynomials),
   REF => 'legendre',
},{
   SOURCE => 'levi',
   DATE => 'March 13, 2009',
   TITLE => qq(Levi-Civitica summation identity),
   REF => 'levi',
},{
   SOURCE => 'locateSatellite',
   DATE => 'April 13, 2008',
   TITLE => qq(Satellite triangulation over sphere),
   REF => 'locateSatellite',
},{
   SOURCE => 'gaGradeDotWedge',
   DATE => 'March 17, 2008',
   TITLE => qq(An earlier attempt to intuitively introduce the dot, wedge, cross, and geometric products),
   REF => 'gaGradeDotWedge',
},{
   REF => 'gaWiki',
   TITLE => qq(Comparison of many traditional vector and GA identities),
   SOURCE => 'gaWiki',
   DATE => 'October 13, 2007',
},{
   SOURCE => 'gaWikiCramers',
   DATE => 'October 16, 2007',
   TITLE => qq(Cramer's rule),
   REF => 'gaWikiCramers',
},{
   SOURCE => 'gaWikiTorque',
   DATE => 'October 13, 2007',
   TITLE => qq(Torque),
   REF => 'gaWikiTorque',
},{
   SOURCE => 'gaussianSurface',
   DATE => 'November 22, 2008',
   TITLE => qq(Gaussian Surface invariance for radial field),
   REF => 'gaussianSurface',
},{
   SOURCE => 'gem',
   DATE => 'October 26, 2008',
   TITLE => qq(GravitoElectroMagnetism),
   REF => 'gem',
},{
   SOURCE => 'gradientAndForms',
   DATE => 'March 31, 2008',
   TITLE => qq(Exterior derivative and chain rule components of the gradient),
   REF => 'gradientAndForms',
},{
   SOURCE => 'lorentz',
   DATE => 'June 25, 2008',
   TITLE => qq(Wave equation based Lorentz transformation derivation),
   REF => 'lorentz',
},{
   REF => 'lorentzForceTx',
   TITLE => qq(Lorentz boost of Lorentz force equations),
   SOURCE => 'lorentzForceTx',
   DATE => 'May 23, 2009',
},{
   REF => 'lorentzRotation',
   TITLE => qq(Lorentz Force Trajectory),
   SOURCE => 'lorentzRotation',
   DATE => 'May 7, 2008',
},{
   REF => 'macroscopicMaxwell',
   TITLE => qq(Macroscopic Maxwell's equation),
   SOURCE => 'macroscopicMaxwell',
   DATE => 'May 28, 2009',
},{
   REF => 'massVaryLagrangian',
   TITLE => qq(Equations of motion given mass variation with spacetime position),
   SOURCE => 'massVaryLagrangian',
   DATE => 'August 28, 2008',
},{
   REF => 'matrixOfLinearTx',
   TITLE => qq(Matrix of grade k multivector linear transformations),
   SOURCE => 'matrixOfLinearTx',
   DATE => 'May 16, 2008',
},{
   REF => 'maxwellsGa',
   TITLE => qq(Maxwell's equations expressed with Geometric Algebra),
   SOURCE => 'maxwellsGa',
   DATE => 'January 29, 2008',
},{
   REF => 'newtonianLagrangianAndGradient',
   TITLE => qq(Newton's Law from Lagrangian),
   SOURCE => 'newtonianLagrangianAndGradient',
   DATE => 'August 9, 2008',
},{
   REF => 'nfcmCh2',
   TITLE => qq(Some NFCM exercise solutions and notes),
   SOURCE => 'nfcmCh2',
   DATE => 'November 27, 2008',
},{
   REF => 'orthodecomp',
   TITLE => qq(Orthogonal decomposition take II),
   SOURCE => 'orthodecomp',
   DATE => 'April 1, 2008',
},{
   REF => 'outermorphismDet',
   TITLE => qq(OuterMorphism Question ),
   SOURCE => 'outermorphismDet',
   DATE => 'September 2, 2008',
},{
   REF => 'pauliMatrix',
   TITLE => qq(Pauli Matrices),
   SOURCE => 'pauliMatrix',
   DATE => 'December 6, 2008',
},{
   REF => 'plane',
   TITLE => qq(More details on NFCM plane formulation),
   SOURCE => 'plane',
   DATE => 'January 1, 2008',
},{
   REF => 'projectionAndMoorePenroseVectorInverse',
   TITLE => qq(Projection and Moore-Penrose vector inverse),
   SOURCE => 'projectionAndMoorePenroseVectorInverse',
   DATE => 'May 16, 2008',
},{
   REF => 'quaternion',
   TITLE => qq(Quaternions),
   SOURCE => 'quaternion',
   DATE => 'February 2, 2008',
},{
   REF => 'reciprocalFrame',
   TITLE => qq(Reciprocal Frame Vectors),
   SOURCE => 'reciprocalFrame',
   DATE => 'March 29, 2008',
},{
   REF => 'scalarCommutes',
   TITLE => qq(Multivector product grade zero terms),
   SOURCE => 'scalarCommutes',
   DATE => 'March 16, 2008',
},{
   REF => 'schCurrent',
   TITLE => qq(Schr\\"{o}dinger equation probability conservation),
   SOURCE => 'schCurrent',
   DATE => 'January 11, 2009',
},{
   REF => 'sgMx41',
   TITLE => qq(Magnetic field between two parallel wires),
   SOURCE => 'sgMx41',
   DATE => 'July 20, 2008',
},{
   REF => 'slerp',
   TITLE => qq(Rotor interpolation calculation),
   SOURCE => 'slerp',
   DATE => 'November 30, 2008',
},{
   REF => 'spacetimegrad',
   TITLE => qq(Lorentz transformation of spacetime gradient),
   SOURCE => 'spacetimegrad',
   DATE => 'July 16, 2008',
},{
   REF => 'tensor',
   TITLE => qq(Gradient and tensor notes),
   SOURCE => 'tensor',
   DATE => 'June 6, 2008',
},{
   REF => 'PJTongMf1',
   TITLE => qq(Solutions to David Tong's mf1 Lagrangian problems),
   SOURCE => 'tongMf1',
   DATE => 'August 25, 2008',
},{
   REF => 'trivector',
   TITLE => qq(Trivector geometry),
   SOURCE => 'trivector',
   DATE => 'March 9, 2008',
},{
   SOURCE => 'velocityTx',
   TITLE => qq(Understanding four velocity transform from rest frame),
   DATE => 'August 13, 2008',
   REF => 'velocityTx',
}) ;

my @nonga =
({
   SOURCE => 'accFourVector',
   DATE => 'April 10, 2009',
   REF => 'accFourVector',
   TITLE => 'Relativistic acceleration',
},{
   SOURCE => 'binomial',
   DATE => 'March 26, 2009',
   REF => 'binomial',
   TITLE => 'Integer binomial theorem induction, the easy dumb way',
},{
   SOURCE => 'bohm11',
   DATE => 'May 8, 2009',
   REF => 'bohm11',
   TITLE => 'QM notes and problems for Bohm, chapter 11',
},{
   SOURCE => 'bohmCh10',
   DATE => 'April 23, 2009',
   REF => 'bohmCh10',
   TITLE => 'Bohm Chapter 10 problems',
},{
   SOURCE => 'bohmCh9',
   DATE => 'March 6, 2009',
   REF => 'bohmCh9',
   TITLE => 'Bohm Chapter 9 problems',
},{
   SOURCE => 'box',
   DATE => 'Jan 0, 0000',
   REF => 'box',
   TITLE => 'box',
},{
   SOURCE => 'byronFullerCalcVar',
   DATE => 'March 21, 2009',
   REF => 'byronFullerCalcVar',
   TITLE => 'Worked calculus of variations problems from Byron and Fuller',
},{
   SOURCE => 'commutatorHerm',
   DATE => 'April 13, 2009',
   REF => 'commutatorHerm',
   TITLE => 'Commutator and Anti-Commutator Hermitian-ness',
},{
   SOURCE => 'constantQ',
   DATE => 'Jan 0, 0000',
   REF => 'constantQ',
   TITLE => 'constant q',
},{
   SOURCE => 'crossOld',
   DATE => 'May 0, 2000',
   REF => 'crossOld',
   TITLE => 'Early cross product generalization and motivation attempt',
},{
   SOURCE => 'cross',
   DATE => 'October 12, 2007',
   REF => 'cross',
   TITLE => 'The cross product in three and more dimensions',
},{
   SOURCE => 'debroglie',
   DATE => 'October 25, 2008',
   REF => 'debroglie',
   TITLE => 'Some notes on DeBroglie paper',
},{
   SOURCE => 'deltaOrthoSeries',
   DATE => 'March 8, 2009',
   REF => 'deltaOrthoSeries',
   TITLE => 'Dirac delta function in terms of orthogonal functions',
},{
   SOURCE => 'distributions',
   DATE => 'March 4, 2009',
   REF => 'distributions',
   TITLE => 'Applications of Fourier distribution theory to some PDEs',
},{
   SOURCE => 'dotLinearity',
   DATE => 'March 13, 2009',
   REF => 'dotLinearity',
   TITLE => 'Dot product linearity by construction',
},{
   SOURCE => 'ehrenfest',
   DATE => 'January 22, 2009',
   REF => 'ehrenfest',
   TITLE => "Ehrenfest's theorem",
},{
   SOURCE => 'emTensor',
   DATE => 'May 30, 2008',
   REF => 'emTensor',
   TITLE => 'Geometric Algebra: Signs of electromagnetic field tensor components',
},{
   SOURCE => 'euler',
   DATE => 'March 0, 2009',
   REF => 'euler',
   TITLE => 'euler',
},{
   SOURCE => 'faradayLagrangian',
   DATE => 'February 0, 2009',
   REF => 'faradayLagrangian',
   TITLE => 'REMOVED FROM electric field energy',
},{
   SOURCE => 'fletcher',
   DATE => 'March 0, 2009',
   REF => 'fletcher',
   TITLE => 'fletcher64',
},{
   SOURCE => 'fvec',
   DATE => 'June 10, 2008',
   REF => 'fvec',
   TITLE => 'Relativistic dynamics from Lagrangian',
},{
   SOURCE => 'gacsQ88',
   DATE => 'May 9, 2008',
   REF => 'gacsQ88',
   TITLE => 'Questioning equation 8.8 from GASC',
},{
   SOURCE => 'gaussian',
   DATE => 'January 05, 2009',
   REF => 'gaussian',
   TITLE => 'Evaluating the Gaussian integral',
},{
   SOURCE => 'goldsteinCh12',
   DATE => 'Sept 02, 2008',
   REF => 'goldsteinCh12',
   TITLE => 'Attempts at solutions for some Goldstein Mechanics problems',
},{
   SOURCE => 'greens',
   DATE => 'December 19, 2008',
   REF => 'greens',
   TITLE => "Green's functions",
},{
   SOURCE => 'harmonicOsc',
   DATE => 'April 19, 2009',
   REF => 'harmonicOsc',
   TITLE => 'Quantum Harmonic Oscillator',
},{
   SOURCE => 'kleinGordon',
   DATE => 'March 27, 2009',
   REF => 'kleinGordon',
   TITLE => 'Some Klein-Gordon equation notes',
},{
   SOURCE => 'longWireQ',
   DATE => 'Jan 0, 0000',
   REF => 'longWireQ',
   TITLE => 'long wire q',
},{
   SOURCE => 'lorentzMetricTensor',
   DATE => 'August 30, 2008',
   REF => 'lorentzMetricTensor',
   TITLE => 'Short metric tensor explanation',
},{
   SOURCE => 'lorentzTxEmPotential',
   DATE => 'October 17, 2008',
   REF => 'lorentzTxEmPotential',
   TITLE => 'Lorentz force interaction',
},{
   SOURCE => 'lutQ0304',
   DATE => 'March 0, 2009',
   REF => 'lutQ0304',
   TITLE => 'lut q0304',
},{
   SOURCE => 'matrixToOperator',
   DATE => 'November 25, 2008',
   REF => 'matrixToOperator',
   TITLE => '2D matrix vs. GA wedge-dot',
},{
   SOURCE => 'maxwell',
   DATE => 'March 25, 2000',
   REF => 'maxwell',
   TITLE => "Various formulations of Maxwell's equations",
},{
   SOURCE => 'mpInverseSvdRoughNotes',
   DATE => 'May 15, 2008',
   REF => 'mpInverseSvdRoughNotes',
   TITLE => 'Singular Value Decomposition',
},{
   SOURCE => 'm',
   DATE => 'Jan 0, 0000',
   REF => 'm',
   TITLE => 'matteo m',
},{
   SOURCE => 'pauliFourVectorV',
   DATE => 'April 8, 2009',
   REF => 'pauliFourVectorV',
   TITLE => 'Four vector velocity addition notes',
},{
   SOURCE => 'pauliQmRelativityIntro',
   DATE => 'January 24, 2009',
   REF => 'pauliQmRelativityIntro',
   TITLE => qq(Pauli's relativity background in QM intro from "Wave Mechanics"),
},{
   SOURCE => 'pe',
   DATE => 'July 28, 2008',
   REF => 'pe',
   TITLE => 'Potential and Kinetic Energy',
},{
   SOURCE => 'pfSch',
   DATE => 'October 14, 2008',
   REF => 'pfSch',
   TITLE => 'pf sch',
},{
   SOURCE => 'pythagoras',
   DATE => 'March 17, 2008',
   REF => 'pythagoras',
   TITLE => 'Pythagoras law',
},{
   SOURCE => 'qmBarrier',
   DATE => 'May 11, 2009',
   REF => 'qmBarrier',
   TITLE => 'One dimensional rectangular Quantum barrier penetration problem',
},{
   SOURCE => 'qmSusskind',
   DATE => 'December 23, 2008',
   REF => 'qmSusskind',
   TITLE => "Notes on Susskind's QM Lecture",
},{
   SOURCE => 'qmbFirstTry',
   DATE => 'May 9, 2009',
   REF => 'qmbFirstTry',
   TITLE => 'VERSION: First try at one dimensional rectangular Quantum barrier problem',
},{
   SOURCE => 'qmdCh2quiz',
   DATE => 'January 12, 2009',
   REF => 'qmdCh2quiz',
   TITLE => 'Chapter 2 Quiz solutions for QM Demystified book',
},{
   SOURCE => 'rapidity',
   DATE => 'December 18, 2008',
   REF => 'rapidity',
   TITLE => 'Some rapidity angle notes',
},{
   SOURCE => 'reviewAlanGabookCh4',
   DATE => 'Jan 0, 0000',
   REF => 'reviewAlanGabookCh4',
   TITLE => 'review alan ch4',
},{
   SOURCE => 'reviewAlanGabook',
   DATE => 'Jan 0, 0000',
   REF => 'reviewAlanGabook',
   TITLE => "Chapter I-III comments on Alan's book",
},{
   SOURCE => 'rindler',
   DATE => 'Jan 0, 0000',
   REF => 'rindler',
   TITLE => 'rindler',
},{
   SOURCE => 'schwartzchildMetric',
   DATE => 'October 2, 2008',
   REF => 'schwartzchildMetric',
   TITLE => 'Some GR Notes',
},{
   SOURCE => 'sch',
   DATE => 'December 13, 2008',
   REF => 'sch',
   TITLE => 'Ad-hoc motivation of some QM wave equations',
},{
   SOURCE => 'scratchPlanewave',
   DATE => 'February 0, 2009',
   REF => 'scratchPlanewave',
   TITLE => 'scratch planewave',
},{
   SOURCE => 'shear',
   DATE => 'April 7, 2008',
   REF => 'shear',
   TITLE => 'Notes on shear transformation',
},{
   SOURCE => 'srLagrangianQ',
   DATE => 'October 0, 2008',
   REF => 'srLagrangianQ',
   TITLE => 'sr lagrangian',
},{
   SOURCE => 'starDistance',
   DATE => 'January 17, 2000',
   REF => 'starDistance',
   TITLE => 'Derive the star distance calculation in the Feynman lectures',
},{
   SOURCE => 'stubEmFields',
   DATE => 'February 0, 2009',
   REF => 'stubEmFields',
   TITLE => 'stub em fields',
},{
   SOURCE => 'tangentspace',
   DATE => 'March 0, 2009',
   REF => 'tangentspace',
   TITLE => 'tangentspace',
},{
   SOURCE => 'taylors',
   DATE => 'February 2, 2008',
   REF => 'taylors',
   TITLE => "Taylor's theorem deviation",
},{
   SOURCE => 'twoNinetyRotations',
   DATE => 'January 17, 2009',
   REF => 'twoNinetyRotations',
   TITLE => 'Composition of rotations exercise',
},{
   SOURCE => 'twobodies',
   DATE => 'December 15, 2008',
   REF => 'twobodies',
   TITLE => 'Time for two bodies to converge in space',
},{
   SOURCE => 'velocityAddition',
   DATE => 'December 25, 2008',
   REF => 'velocityAddition',
   TITLE => 'Some notes on Pauli Relativity Velocity addition',
},{
   SOURCE => 'voltageCurrentResistance',
   DATE => 'May 3, 2009',
   REF => 'voltageCurrentResistance',
   TITLE => 'Voltage current, and resistance',
},{
   SOURCE => 'waveLagrangian',
   DATE => 'December 02, 2008',
   REF => 'waveLagrangian',
   TITLE => "Compare some wave equation's and their Lagrangians",
},{
   SOURCE => 'wavepacket',
   DATE => 'February 16, 2009',
   REF => 'wavepacket',
   TITLE => 'Simple Wave Packet Examples',
},{
   SOURCE => 'wavevariation',
   DATE => 'April 27, 2009',
   REF => 'wavevariation',
   TITLE => 'Simple minded variation of one dimensional wave equation Lagrangian',
},{
   SOURCE => 'wedgeNormVsGaNorm',
   DATE => 'January 0, 2008',
   REF => 'wedgeNormVsGaNorm',
   TITLE => 'Wedge product norm and GA bivector norm comparison',
}
) ;

my %monthsOfYear = (
'January' => 1,
'February' => 2,
'March' => 3,
'April' => 4,
'May' => 5,
'June' => 6,
'July' => 7,
'August' => 8,
'September' => 9,
'October' => 10,
'November' => 11,
'December' => 12
) ;

dumpem() ;
#checkDate() ;

exit ;

sub dumpem
{
   my @sorted ;

   if ( $doGabook )
   {
      @sorted = sort datesort @gabook ;
   }
   else
   {
      @sorted = sort datesort @nonga ;
   }

   print "\\chapter{Cronological Index}\n\\begin{itemize}\n\n" ;
   foreach (@sorted)
   {
      my ($source, $title, $date, $ref) 
         = ( $_->{'SOURCE'},
             $_->{'TITLE'},
             $_->{'DATE'},
             $_->{'REF'} ) ;

      print "\\item $date \\ref{chap:$ref} $title\n\n" ;
   }
   print "\\end{itemize}\n" ;
}

#sub testm
#{
#print $monthsOfYear{'July'} ;
#}

sub checkDate
{
   foreach (@nonga)
   {
      my $bdate = $_->{'DATE'} ;
      die "date parse: $bdate : $$a\n" unless ( $bdate =~ /(\S+)\s+(\d+)\s*,\s*(\d+)\s*/ ) ;
   }
}

sub datesort
{
   my ($adate, $bdate) = ( $$a{'DATE'}, $$b{'DATE'} ) ;

#   my ($asource, $atitle, $adate, $aref) 
#         = ( $$a{'SOURCE'},
#             $$a{'TITLE'},
#             $$a{'DATE'},
#             $$a{'REF'} ) ;
#
#   my ($bsource, $btitle, $bdate, $bref) 
#         = ( $$b{'SOURCE'},
#             $$b{'TITLE'},
#             $$b{'DATE'},
#             $$b{'REF'} ) ;

   die "date parse: $adate : $$a\n" unless ( $adate =~ /(\S+)\s+(\d+)\s*,\s*(\d+)\s*/ ) ;
   my ($amonth, $aday, $ayear) = ($1, $2, $3) ;

   die "date parse: $bdate : $$b\n" unless ( $bdate =~ /(\S+)\s+(\d+)\s*,\s*(\d+)\s*/ ) ;
   my ($bmonth, $bday, $byear) = ($1, $2, $3) ;

   my $rc = $ayear <=> $byear ;
   if ( !$rc )
   {
      $rc = $monthsOfYear{$amonth} <=> $monthsOfYear{$bmonth} ;

      if ( !$rc )
      {
         $rc = $aday <=> $bday ;
      }
   }

   return $rc ;
}
