ORDERED += ../slides/01_lecture.pdf
ORDERED += PHY487_L1.pdf
ORDERED += ../slides/02_lecture.pdf
ORDERED += PHY487_L02.pdf
ORDERED += ../slides/03_lecture.pdf
ORDERED += PHY487_L03.pdf
ORDERED += ../slides/04_lecture.pdf
ORDERED += Phy487_L04.pdf
ORDERED += ../slides/05_lecture.pdf
ORDERED += Phy487_L05.pdf
ORDERED += Phy487_L06.pdf
ORDERED += ../slides/07_lecture.pdf
ORDERED += Phy487_L07.pdf
ORDERED += ../slides/08_lecture.pdf
ORDERED += Phy487_L08.pdf
ORDERED += ../slides/09_lecture.pdf
ORDERED += Phy487_L09.pdf
ORDERED += ../slides/10_lecture.pdf
ORDERED += Phy487_L10.pdf
ORDERED += ../slides/11_lecture.pdf
ORDERED += Phy487_011.pdf
ORDERED += Phy487_L012.pdf
ORDERED += ../slides/13_lecture.pdf
ORDERED += Phy487_L13.pdf
ORDERED += ../slides/14_lecture.pdf
ORDERED += Phy487_L14.pdf
ORDERED += ../slides/15_lecture.pdf
ORDERED += Phy487_L15.pdf
ORDERED += ../slides/16_lecture.pdf
ORDERED += Phy487_L16.pdf
ORDERED += Phy487_L17.pdf
ORDERED += ../slides/18_lecture.pdf
ORDERED += Phy487_L18.pdf
ORDERED += ../slides/19_lecture.pdf
ORDERED += Phy487_L19.pdf
ORDERED += Phy487_L020.pdf
ORDERED += ../slides/21_lecture.pdf
ORDERED += Phy487_L21.pdf
ORDERED += Phy487_L22.pdf

all: handouts.pdf

handouts.pdf : $(ORDERED) GNUmakefile
	pdftk $(ORDERED) cat output $@
