#!/usr/bin/perl

# check directory listings of this dir and ../slides/ against the ordered list in 
# GNUmakefile that generates the concatonated handouts.pdf

my %g = () ;
open my $fh, "GNUmakefile" or die ;
while (<$fh>)
{
   chomp ;

   next unless ( s/^ORDERED \+= *// ) ;

   $g{$_}++ ;   
}
close $fh ;

my %h = map {$_ => 1} (<P*pdf ../slides/*pdf>) ;
foreach (keys %h)
{
   if ( !defined $g{$_} )
   {
      print "ORDERED += $_\n" ;
   }
}
