#!/usr/bin/perl

use strict ;
use warnings ;
use Getopt::Long ;
my $deltext ;
my $dollar ;
my $help ;

GetOptions
( 
   'delimter=s'      => \$deltext,
   'dollar!'         => \$dollar,
   'help!'           => \$help,
) ;

if ( defined $help )
{
   print "del2xml [-help] [-delimter blah] [-dollar]\n" .
         "\n" .
         "Options:\n" .
         "\t-dollar\tUse '\$' as a delimiter.\n" .
         "\t-delimiter blah\tUse 'blah' as a delimiter.\n" .
         "\n" .
         "Default delimiter is '[opt-spaces],[opt-spaces]\n" .
         "" ;

   exit 1 ;
}

my $delimiter ;
if ( defined $dollar )
{
   $delimiter = qr(\$) ;
}
elsif ( defined $deltext )
{
   $delimiter = qr($deltext) ;
}
else
{
   $delimiter = qr(\s*,\s*) ; # opt-spaces comma opt-spaces
}

my @headers ;
my $tags ;
print "<head>\n" ;

while ( <> )
{
   chomp ;
   my @e = split( $delimiter, $_ ) ;
   my $columns = scalar( @e ) ; 

   if ( defined $tags )
   {
      die "columns != tags: $columns, $tags\n" if ( $columns != $tags ) ;

      print "<line>\n" ;
      for ( my $i = 0 ; $i < scalar(@e) ; $i++ )
      {
         print "<$headers[$i]>$e[$i]</$headers[$i]>\n" ;
      }
      print "</line>\n" ;
   }
   else
   {
      @headers = @e ;
      $tags = $columns ;
   }
}
print "</head>\n" ;
