# these samples are from:
#  http://www.ieee.org/documents/IEEEtran.zip

include ../latex/make.vars

# don't care about peeter's .sty stuff here
COPIED_FILES := 

#ONCEFLAGS := -justonce

GENERATED_PDFS := $(subst tex,pdf,$(shell echo *.tex))

include ../latex/make.rules
