qftProblemSet1.pdf : ../phy2403/qftProblemSet1Problem1.tex
qftProblemSet1.pdf : ../phy2403/qftProblemSet1Problem2.tex
qftProblemSet1.pdf : ../phy2403/qftProblemSet1Problem3.tex
qftProblemSet1.pdf : ../phy2403/qftProblemSet1Problem4.tex
qftProblemSet1.pdf : ../phy2403/qftProblemSet1Problem5.tex
qftProblemSet1.pdf : ../phy2403/qftProblemSet1Problem6.tex
