#-------------------------------------------------
# Built two versions of clang, one for debugging
# into rewritersample.cpp:
#-------------------------------------------------
CONFIG_RELEASE = Release+Asserts
CLANGPATH=$(HOME)/clang/optimized48rt
#-------------------------------------------------
#CONFIG_RELEASE = Debug+Asserts
#CLANGPATH=$(HOME)/clang/debug48rt
#-------------------------------------------------

CFLAGS += -gdwarf-2
CFLAGS += -I$(CLANGPATH)/include
CONFIG_RELEASE = Release+Asserts
#-------------------------------------------------
# local clang build related stuff:

CXX := $(CLANGPATH)/bin/clang++
#CXX := $(CLANGPATH)/bin/g++

LLVM_BIN_PATH := $(CLANGPATH)/bin/

LDFLAGS += -L$(CLANGPATH)/lib64
LDFLAGS += -Wl,-rpath,$(CLANGPATH)/lib64
LDFLAGS += -Wl,-rpath-link,$(CLANGPATH)/lib64
