GCCPATH := $(HOME)/local/gcc520
RUNTIMEPATH := $(GCCPATH)/lib64

ifdef USE_GCC
   CXX := $(GCCPATH)/bin/g++
else
   ifdef USE_CLANG35
      CLANGPATH=$(HOME)/clang350.debug
      RUNTIMEPATH=$(CLANGPATH)/lib64
   else
      # this clang built with gcc-5.2 runtime:
      CLANGPATH=$(HOME)/local/clang362.opt
   endif
   CXX := $(CLANGPATH)/bin/clang++
endif

#CFLAGS += -gdwarf-2

LDFLAGS += -L$(RUNTIMEPATH)
LDFLAGS += -Wl,-rpath,$(RUNTIMEPATH)
LDFLAGS += -Wl,-rpath-link,$(RUNTIMEPATH)
